# Generated by Django 5.2.1 on 2025-05-13 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients_suppliers', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Identifier')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.TextField(verbose_name='Scope')),
                ('milestones', models.TextField(blank=True, verbose_name='Milestones')),
                ('billing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='manager.billingtype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients_suppliers.party')),
                ('payment_interval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='manager.paymentinterval')),
                ('service_types', models.ManyToManyField(blank=True, to='manager.servicetype')),
                ('technologies', models.ManyToManyField(blank=True, to='manager.technology')),
            ],
        ),
    ]
