# Generated by Django 5.2.1 on 2025-05-13 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients_suppliers', '0001_initial'),
        ('contracts', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('scope', models.TextField(verbose_name='Scope')),
                ('main_contact', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('rate_or_value', models.DecimalField(blank=True, decimal_places=2, help_text='Fill if billing is hourly or fixed.', max_digits=10, null=True, verbose_name='Rate/Value')),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='manager.billingtype')),
                ('client', models.ForeignKey(blank=True, help_text='Set when no contract.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients_suppliers.party')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contracts.contract')),
                ('payment_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='manager.paymentinterval')),
                ('technologies', models.ManyToManyField(blank=True, to='manager.technology')),
            ],
        ),
    ]
