
name: Django CI/CD

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations (Neon or local)
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_ENV: dev
          NEON_DEV_URL: ${{ secrets.NEON_DEV_URL }}
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_ENV: dev
          NEON_DEV_URL: ${{ secrets.NEON_DEV_URL }}
        run: |
          python manage.py test

# Futuro: job de deploy pode ser adicionado aqui (ex: deploy via Portainer, rsync, SSH, etc.)
