# Generated by Django 5.2.1 on 2025-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtype',
            name='mode',
            field=models.CharField(choices=[('fixed', 'Valor Fixo'), ('hourly', 'Valor por Hora')], default='fixed', max_length=64, verbose_name='Mode'),
        ),
    ]
